### ISSUE TITLE
how to make it release the incremental part to medium

### ISSUE THREAD

**Issue by daiwa233** [InfraWay/post-medium-action#2]

**Comment by maZahaca** [comment]
Hello,

Can you provide a bit more details of what are you trying to do?
In general action allows you to release a markdown file to Medium.

**Comment by daiwa233** [comment]
I want to use this action to publish the markdown file to medium every time I commit.
But now my understanding of this action, the configuration item markdown_file is a fixed value?

btw, how to get app_id.

![image](https://user-images.githubusercontent.com/50663255/107614884-21989f80-6c86-11eb-8ca3-16d43885db55.png)

When i click on that link，I got:

![image](https://user-images.githubusercontent.com/50663255/107614992-560c5b80-6c86-11eb-949f-953d9e5c1b02.png)

**Comment by maZahaca** [comment]
To get `app_id` you need to:
1. Login on Medium
2. Visit page https://medium.com/me/applications
3. Create new application

**Comment by maZahaca** [comment]
So, this action does minimal thing - it publishes whatever we tell it to publish.

Here is a hack how you can determine changed files and detect markdown files from it:

```
    - id: files
      uses: jitterbit/get-changed-files@v1
    - id: posts
      name: Detecting posts from the changes
      run: |
        i=0
        for changed_file in ${{ steps.files.outputs.added_modified }}; do
          echo "Do something with ${changed_file}."
          if [[ "${changed_file}" == "content/posts"* ]];
          then
            echo "File ${changed_file} matched post."
            echo "::set-output name=post${i}::${changed_file}"
            ((i=i+1))
          fi
        done
    - if: steps.posts.outputs.post0
      name: Publish to medium
      uses: infraway/post-medium-action@v1.2.0
      with:
        app_id: ${{ secrets.MEDIUM_APP_ID }}
        app_secret: ${{ secrets.MEDIUM_APP_SECRET }}
        access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
        markdown_file: ${{ steps.posts.outputs.post0 }}
        base_url: https://myblog.com
```

This part filters files from directory where all post are.
`"${changed_file}" == "content/posts"* `

I will extend documentation with this example

**Comment by maZahaca** [comment]
It's released in here -> https://github.com/InfraWay/post-medium-action/releases/tag/v1.3.0

**Comment by daiwa233** [comment]
> To get `app_id` you need to:
> 
> 1. Login on Medium
> 2. Visit page https://medium.com/me/applications
> 3. Create new application

yes, I have already login on Medium, but when I navigate to " https://medium.com/me/applications", and then I entered a page that says I don't have permission

OK, fine. I will explore this problem myself

**Comment by daiwa233** [comment]
> So, this action does minimal thing - it publishes whatever we tell it to publish.
> 
> Here is a hack how you can determine changed files and detect markdown files from it:
> 
> ```
>     - id: files
>       uses: jitterbit/get-changed-files@v1
>     - id: posts
>       name: Detecting posts from the changes
>       run: |
>         i=0
>         for changed_file in ${{ steps.files.outputs.added_modified }}; do
>           echo "Do something with ${changed_file}."
>           if [[ "${changed_file}" == "content/posts"* ]];
>           then
>             echo "File ${changed_file} matched post."
>             echo "::set-output name=post${i}::${changed_file}"
>             ((i=i+1))
>           fi
>         done
>     - if: steps.posts.outputs.post0
>       name: Publish to medium
>       uses: infraway/post-medium-action@v1.2.0
>       with:
>         app_id: ${{ secrets.MEDIUM_APP_ID }}
>         app_secret: ${{ secrets.MEDIUM_APP_SECRET }}
>         access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
>         markdown_file: ${{ steps.posts.outputs.post0 }}
>         base_url: https://myblog.com
> ```
> 
> This part filters files from directory where all post are.
> `"${changed_file}" == "content/posts"* `
> 
> I will extend documentation with this example

I get it , thank you every much
