### ISSUE TITLE
Medium's settings page only creates two strings for credentials

### ISSUE THREAD

**Issue by higgins** [InfraWay/post-medium-action#3]
Hello and thank you for making this action!

Looking to integrate it on a project but when I create Integration tokens at https://medium.com/me/settings, I'm only returned two strings. I assume they are `app_id` and `app_secret` or `app_secret` and `access_token`.

How do I generate the third required input?

UPDATE:
It actually looks like Medium only returns one value (but they wrap the text with break-word so it looked like two). How do I generate the other 2 required inputs and which corresponds to which?

**Comment by maZahaca** [comment]
Hello! Happy to hear that

So, you actually need to generate just two things:
1. An app (app_id, app_secret) -> https://medium.com/me/applications
2. Personal access token (access_token) -> https://medium.com/me/settings

This should be listed in [README.md](https://github.com/InfraWay/post-medium-action#readme) file.

**Comment by higgins** [comment]
The `/me/applications` page 403's for me
<img width="1404" alt="Screen Shot 2021-11-22 at 3 21 22 PM" src="https://user-images.githubusercontent.com/876147/142949611-05b02365-7d55-4f15-9240-c9b34eab503c.png">

Their support team told me:
```
We don't allow any new integrations with our API.

The Medium API is only available for an integration token for use with third-party writing applications, such as:

    iA Writer
    Ulysses
```

Kind of a bummer if it means I can't use their SDK :/

**Comment by maZahaca** [comment]
Let me check if it works without app_id and app_secret

**Comment by maZahaca** [comment]
I've raised a related issue https://github.com/Medium/medium-sdk-nodejs/issues/36

Based on their response, I will amend the action to make it work without app_id, app_secret. It may take some time.

**Comment by maZahaca** [comment]
Hey @higgins, I'm planning to replace this SDK with a tiny manual implementation of required methods, will get back soon, when it's done.

Finally, it will be using just a personal access token.

**Comment by higgins** [comment]
@maZahaca awesome and thank you! take your time!

**Comment by maZahaca** [comment]
@higgins just fixed it in new version https://github.com/InfraWay/post-medium-action/releases/tag/v1.5.0

Please, follow updated docs https://github.com/InfraWay/post-medium-action#readme

**Comment by higgins** [comment]
@maZahaca Excellent! Thanks for the quick fix!
