### ISSUE TITLE
I cannot get publish my posts on Medium. The workflow it's jumping publish step

### ISSUE THREAD

**Issue by renatogodois** [InfraWay/post-medium-action#5]
I am facing some issue to publish posts on Medium by workflow.
The publish step it's jumping:

![image](https://user-images.githubusercontent.com/55892812/157515802-2c41b6fe-f799-4879-bb3a-086093a5f953.png)

**Comment by maZahaca** [comment]
Hello!
Could you share here your GitHub workflow definition for clarity?

**Comment by renatogodois** [comment]
name: publish-to-medium
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - id: posts
        name: Detecting posts from the changes
        run: |
          i=0
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo "Do something with ${changed_file}."
            if [[ "${changed_file}" == "my-medium/posts"* ]];
            then
              echo "File ${changed_file} matched post."
              echo "::set-output name=post${i}::${changed_file}"
              ((i=i+1))
            fi
          done
      - if: steps.posts.outputs.post0
        name: Publish to medium
        uses: InfraWay/post-medium-action@v1.6.0
        with:
          access_token: ${{ secrets.MEDIUM }}
          markdown_file: ${{ steps.posts.outputs.post0 }}
          base_url: https://medium.com/@renatogodois
          post_status: draft

**Comment by maZahaca** [comment]
I believe “if” is not satisfied, that’s the reason why workflow skips it

**Comment by renatogodois** [comment]
So you suggest to take out the "if"?

**Comment by renatogodois** [comment]
I fixed the issue. Was necessary include "- uses: actions/checkout@v2" before "if". After that, the post was published without errors. Thx!!!
