### ISSUE TITLE
Error: Cannot find module '@redcode/medium-sdk'

### ISSUE THREAD

**Issue by Chieze-Franklin** [InfraWay/post-medium-action#7]
Hi there,

I'm getting the error pictured below.

![image](https://user-images.githubusercontent.com/6097630/212012267-c66b1671-0513-4af8-ba5a-d4f679550a57.png)

**Comment by maZahaca** [comment]
Hello!

Thanks for the report! It's been fixed in version [v1.6.0](https://github.com/InfraWay/post-medium-action/releases/tag/v1.6.0)

For now, I also fixed the example in the readme.

**Comment by maZahaca** [comment]
Feel free to reopen it if still reproduces
